---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "youtube-stats-chart.fullname" . }}-secrets
type: Opaque
data:
    YOUTUBE_API_KEY: "{{ .Values.youtubeStatsSettings.ytAPIKey | default "" | b64enc }}"
    YOUTUBE_CHANNEL_ID: "{{ .Values.youtubeStatsSettings.ytChannelID | default "" | b64enc }}"